### PR TITLE
Add FuckingReduceSyntax to projects

### PR DESCRIPTION
**Pull request by schmidyy**

### CODE REVIEW

**Comment by SamWheating** [comment]
Looks good, can I see a screenshot before I approve? We have to make sure it remains responsive / fits on a screen so we might need to resize text as we add content.

**Comment by schmidyy** [comment]
Looks ok on Apple Watch:

image

Can anyone check on a fit bit?

**Comment by SamWheating** [comment]
What does the projects page look like tho?

**Comment by SamWheating** [comment]
Also, nice shirt

**Pull request merged**
